services:
  migrate:
    image: ghcr.io/zaupower/gym-training-guide-yates-style-hit:latest
    container_name: trainlog-migrate
    command: node node_modules/prisma/build/index.js migrate deploy
    environment:
      DATABASE_URL: postgresql://postgress:p0stgre55@192.168.0.112:5432/trainlog?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"

  app:
    image: ghcr.io/zaupower/gym-training-guide-yates-style-hit:latest
    container_name: trainlog-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://postgress:p0stgre55@192.168.0.112:5432/trainlog?schema=public
      NODE_ENV: production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migrate:
        condition: service_completed_successfully
