services:
  migrate:
    image: ghcr.io/zaupower/gym-training-guide-yates-style-hit:latest
    container_name: trainlog-migrate
    command: node node_modules/prisma/build/index.js migrate deploy
    environment:
      DATABASE_URL: postgresql://postgress:p0stgre55@192.168.0.112:5432/trainlog?schema=public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"

  app:
    image: ghcr.io/zaupower/gym-training-guide-yates-style-hit:latest
    container_name: trainlog-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://postgress:p0stgre55@192.168.0.112:5432/trainlog?schema=public
      NODE_ENV: production
      AUTH_SECRET: 9f2715e59909069b30da8df1d684df77c26b1c3521fbe0765ed764b8bc988656
      COOKIE_SECURE: "false"
      RESEND_API_KEY: re_Bais44e....
      EMAIL_FROM: onboarding@resend.dev
      APP_URL: http://192.168.0.112:3002
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migrate:
        condition: service_completed_successfully
